---
enable-formatter: true
message-on-insufficient-build-permission: You don't have permission to build here.
message-on-insufficient-permissions: You don't have permission to do that.
message-on-group-change: Ta-da! Your group has been changed into... a / an {GROUP}!
...